package com.bvlangen.kungfu.todolist.model;

public enum Todo {
    BED_OPMAKEN,
    PERSOONLIJKE_DINGEN_OPRUIMEN,
    VUILE_KLEREN_IN_DE_WAS_DOEN,
    PERSOONLIJKE_HYGIENE,
    SCHONE_KLEDING_EN_SCHOENEN,
    GEZOND_ETEN,
    HUISWERK_MAKEN,
    PE_INZET_GEBRUIKEN,
    PE_RESPECT_TONEN_LERAREN_EN_VRIENDEN,
    TOEGEWEZEN_TAKEN_AFMAKEN,
    PE_RESPECT_TONEN_HELE_GEZIN,
    JONGERE_BROER_OF_ZUS_HELPEN,
    VIJFTIEN_MIN_WINGTC_EZCRIMA_TRAINEN,
    VOOR_KORTE_TERMIJN_WAARDEVOL_DOEL_STELLEN,
    BLIJF_LETTEN_OP_DE_GESCHREVEN_DOELEN
}
